# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship(5d115e0c-9c03-4bca-99f5-c4c786648327)'
    ScriptType: 'InlineScript'
    Inline: |
      echo "I am running"
    errorActionPreference: 'continue'
    preferredAzurePowerShellVersion: '3.1.0'